### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Selmar** [tszalay/FFTWSharp#1]
Hey there,

A license is missing. I would like to use this wrapper for one of my (possibly commercial) projects, but the default license prohibits me from reproducing, distributing, or creating derivative works from your code. 

Was this your intention? Otherwise, could you maybe add a license allowing me to use and modify the code?
- Selmar

**Comment by tszalay** [comment]
Oops, good point. I've added an MIT license file, go for it.

-Tamas

**Comment by derodriguezat** [comment]
Hey guys,

With the licence that Tamas has added is it possible to use this for a commercial project? Thanks in advance.

Best Regards.

**Comment by tszalay** [comment]
I believe the MIT license permits this, yes, as long as the license is included with the code somewhere:

https://tldrlegal.com/license/mit-license
